# Generated by Django 2.1.3 on 2018-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogUsuarioSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_sistema', models.CharField(blank=True, max_length=350, null=True)),
                ('data_log', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=50, null=True)),
                ('posto_graduacao', models.CharField(blank=True, choices=[('Coronel', 'Coronel'), ('Tenente-Coronel', 'Tenente-Coronel'), ('Major', 'Major'), ('Capitão', 'Capitão'), ('1º Tenente', '1º Tenente'), ('2º Tenente', '2º Tenente'), ('Aspirante', 'Apirante'), ('Aluno-Oficial', 'Aluno-Oficial'), ('Aluno-CHOA', 'Aluno-CHOA'), ('Subtenente', 'Subtenente'), ('1º Sargento', '1º Sargento'), ('Aluno-CAS', 'Aluno-CAS'), ('2º Sargente', '2º Sargento'), ('3º Sargento', '3º Sargento'), ('Aluno-CFS', 'Aluno-CFS'), ('Cabo', 'Cabo'), ('Aluno-Cabo', 'Aluno-Cabo'), ('Soldado', 'Soldado'), ('Aluno-Soldado', 'Aluno-Soldado')], max_length=50, null=True)),
                ('matricula', models.IntegerField(blank=True, null=True)),
                ('rg_pm', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=50, null=True)),
                ('lotacao', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_usuario', models.IntegerField(blank=True, choices=[('1', 'Básico'), ('2', 'Analista'), ('3', 'Administador')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='logusuariosistema',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=False, to='app_usuario.UsuarioSistema'),
        ),
    ]
