# Generated by Django 2.1.3 on 2018-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logusuariosistema',
            name='data_log',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='posto_graduacao',
            field=models.CharField(blank=True, choices=[('Cel', 'Coronel'), ('Ten-Cel', 'Tenente-Coronel'), ('Maj', 'Major'), ('Cap', 'Capitão'), ('1º Ten', '1º Tenente'), ('2º Ten', '2º Tenente'), ('As-Of', 'Apirante'), ('Al-Of', 'Aluno-Oficial'), ('Al-CHOA', 'Aluno-CHOA'), ('St', 'Subtenente'), ('1º Sgt', '1º Sargento'), ('Al-CAS', 'Aluno-CAS'), ('2º Sgt', '2º Sargento'), ('3º Sgt', '3º Sargento'), ('Al-CFS', 'Aluno-CFS'), ('Cb', 'Cabo'), ('Al-Cb', 'Aluno-Cabo'), ('Sd', 'Soldado'), ('Al-Sd', 'Aluno-Soldado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosistema',
            name='tipo_usuario',
            field=models.IntegerField(blank=True, choices=[(1, 'Básico'), (2, 'Analista'), (3, 'Administador')], null=True),
        ),
    ]
