# Generated by Django 2.1.3 on 2018-12-05 14:29

import app_individuo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cor_pele', models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Parda', 'Parda'), ('Negra', 'Negra'), ('Amarela', 'Amarela')], max_length=50, null=True)),
                ('cor_olho', models.CharField(blank=True, choices=[('Azuis', 'Azuis'), ('Verdes', 'Verdes'), ('Casatanhos', 'Castanhos'), ('Pretos', 'Pretos')], max_length=50, null=True)),
                ('cor_cabelo', models.CharField(blank=True, choices=[('Pretos', 'Pretos'), ('Castanhos-escuro', 'Castanhos-escuro'), ('Castanhos-claro', 'Castanhos-claro'), ('Loiros', 'Loiros'), ('Ruivos', 'Ruivos'), ('Outros', 'Outros')], max_length=50, null=True)),
                ('tipo_cabelo', models.CharField(blank=True, choices=[('Liso', 'Liso'), ('Ondulado', 'Ondulado'), ('Encaracolado', 'Encaracolado'), ('Crespo', 'Crespo')], max_length=50, null=True)),
                ('marcas_endemica', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conjunto', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosUnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('numero_habilitacao', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_carteira_trabalho', models.IntegerField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=9, null=True)),
                ('orgao_expedidor', models.CharField(blank=True, max_length=5, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=250, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('quadra', models.CharField(blank=True, max_length=4, null=True)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('bairro', models.ForeignKey(blank=True, on_delete=False, to='app_individuo.Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens', models.ImageField(blank=True, null=True, upload_to=app_individuo.models.uploadPasta)),
            ],
        ),
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=50, null=True)),
                ('alcunha', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=50, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=50, null=True)),
                ('faccao', models.CharField(blank=True, max_length=50, null=True)),
                ('caracteristicas', models.OneToOneField(blank=True, on_delete=False, to='app_individuo.Caracteristicas')),
                ('documento_unico', models.OneToOneField(blank=True, on_delete=False, to='app_individuo.DocumentosUnico')),
                ('endereco', models.ManyToManyField(blank=True, to='app_individuo.Endereco')),
                ('imagem', models.ManyToManyField(blank=True, to='app_individuo.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Tatuagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tatuagem', models.ImageField(blank=True, null=True, upload_to=app_individuo.models.uploadPasta)),
                ('descricao_tatuagem', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='individuo',
            name='tatuagem',
            field=models.ManyToManyField(blank=True, to='app_individuo.Tatuagem'),
        ),
    ]
