# Generated by Django 2.1.3 on 2018-12-06 14:19

import app_individuo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_individuo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='cpf',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app_individuo.DocumentosUnico'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to=app_individuo.models.uploadPasta),
        ),
        migrations.AlterField(
            model_name='tatuagem',
            name='tatuagem',
            field=models.ImageField(blank=True, null=True, upload_to=app_individuo.models.uploadPasta),
        ),
    ]
