# Generated by Django 2.1.3 on 2018-12-06 14:24

import app_individuo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_individuo', '0004_auto_20181206_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to=app_individuo.models.uploadPasta),
        ),
        migrations.AlterField(
            model_name='tatuagem',
            name='tatuagem',
            field=models.ImageField(blank=True, null=True, upload_to=app_individuo.models.uploadPasta),
        ),
    ]
